In [2]:
import cv2
import matplotlib.pyplot as plt
import numpy as np


image_path = '../data/IMG_5572.jpeg'
img = cv2.imread(image_path)
img_HSV = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

In [4]:
img_HSV.shape

(1521, 1010, 3)

In [3]:
for i in range(img_HSV.shape[-1]):
    data = img_HSV[:,:,i]
    print(np.histogram(data, bins=10, density=True))

(array([1.62491605e-02, 1.95823291e-02, 1.70127753e-03, 8.62421372e-04,
       7.43147932e-03, 9.91113623e-03, 7.30958025e-05, 6.14586598e-06,
       4.58212493e-06, 4.42938744e-05]), array([  0. ,  17.9,  35.8,  53.7,  71.6,  89.5, 107.4, 125.3, 143.2,
       161.1, 179. ]))
(array([2.04854294e-02, 7.39017631e-03, 2.63303973e-03, 1.02092353e-03,
       2.47867460e-03, 1.11006576e-03, 5.76514317e-04, 2.30324924e-03,
       1.19420458e-03, 2.34087685e-05]), array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
       229.5, 255. ]))
(array([0.0001063 , 0.00062979, 0.00038314, 0.00079319, 0.00272481,
       0.00173909, 0.00904362, 0.01304384, 0.00580629, 0.00494561]), array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
       229.5, 255. ]))
